# apiVersion: v1
# kind: Namespace
# metadata: 
#   name: flask-api-ns

---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: data-api
  name: data-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: data-api
  template:
    metadata:
      labels:
        k8s-app: data-api
    spec:
      containers:
        - name: data-api
          image: wall404/flask-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---

apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: data-api
  namespace: default
  name: data-api-svc
spec:
  # type: NodePort
  selector:
    k8s-app: data-api
  ports:
    - port: 443
      targetPort: 5000
  externalIPs:
    - 192.168.137.67
---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  name: data-api-ingress
  annotations:
    kubernetes.io/ingress.class: "cafe-ingress"
spec:
  rules: 
  - host: api.swagger.local
    http:
      paths:
      - path: /
        backend:
          serviceName: data-api-svc
          servicePort: 5000